print(" * * * Bienvenido al Generador de Nombres de Cervecerias * * *")
nombre1 = input("Dime el nombre de la ciudad donde naciste:")
nombre2 = input("Dime tu estación del año favorita en inglés:")
print(" - El Nombre de tu cerveceria es:")
print("     \"" + nombre1 + " " + nombre2 + " Brewing Co" + "\" ")